### ISSUE TITLE
The code no longer works?

### ISSUE THREAD

**Issue by knguyen0105** [depfish/91porn#1]
I tested out the script successfully last month. Today I tried running it again but it seems nothing is downloaded. Is it still working? Thanks,

**Comment by depfish** [comment]
can you post the error ?

**Comment by knguyen0105** [comment]
There is no error. I run `python 91porn.py` and it just hang forever.

**Comment by depfish** [comment]
this maybe the network jam

**Comment by depfish** [comment]
thanks for your feedback,I'll improve the scripts later

**Comment by Shujian2015** [comment]
发现这句卡住了：r = getContent(url)

**Comment by Shujian2015** [comment]
我这儿改成这样就可以用了：url = 'http://91porn.com/v.php?category=rf&viewtype=basic'

**Comment by knguyen0105** [comment]
That's it. Worked. Thanks.
